apiVersion: v1
kind: Pod
metadata:
  name: perfinsights-consumer
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - "sleep inf"
    image: quay.io/pbertera/ocp-perfinsights
    imagePullPolicy: Always
    name: perfinsights
    volumeMounts:
    - mountPath: /report
      name: report
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/hostname: ocp4-4zmld-ipi-fzsk7-master-0
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  volumes:
  - name: report
    persistentVolumeClaim:
      claimName: report-pvc
