---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: perfinsights
  labels:
    app: perfinsights
    component: perfinsights
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perfinsights-sa-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-privileged-scc
subjects:
  - kind: ServiceAccount
    name: perfinsights
